function setData_BoxSci(tor,pos,vel,acc,idTrial,tSync,nRate)

sSignalList     = fieldnames(tor);
idSession       = getMeta('metaTrial',qry('idTrial',idTrial),'idSession');
idTrialType     = getMeta('metaTrial',qry('idTrial',idTrial),'idTrialType');

for iSignal = 1:numel(sSignalList)
    setSignal(tor.(sSignalList{iSignal})',qry('sTable','JointTorqueMean',...
        'sSignal',sSignalList{iSignal}),idTrial,...
        'nRate',nRate,...
        'sUnit','Nm',...
        'idSession',idSession,...
        'idTrialType',idTrialType,...
        'tSync',tSync);
    setSignal(pos.(sSignalList{iSignal})',qry('sTable','JointAngleMean',...
        'sSignal',sSignalList{iSignal}),idTrial,...
        'nRate',nRate,...
        'sUnit','rad',...
        'idSession',idSession,...
        'idTrialType',idTrialType,...
        'tSync',tSync);
    setSignal(vel.(sSignalList{iSignal})',qry('sTable','JointVelMean',...
        'sSignal',sSignalList{iSignal}),idTrial,...
        'nRate',nRate,...
        'sUnit','rad/s',...
        'idSession',idSession,...
        'idTrialType',idTrialType,...
        'tSync',tSync);
    setSignal(acc.(sSignalList{iSignal})',qry('sTable','JointAccMean',...
        'sSignal',sSignalList{iSignal}),idTrial,...
        'nRate',nRate,...
        'sUnit','rad/s2',...
        'idSession',idSession,...
        'idTrialType',idTrialType,...
        'tSync',tSync);
end